#!/usr/bin/env python3
# This file is placed in the Public Domain.


"lint"


import os


SKIP = ["---", "Your code"]
IGNORE = "C,R,E0402,E0401,E1101,W0201,W0703,W0613,W0108,W0406,W0212,W0622"


def doskip(txt):
    if not txt.strip():
        return True
    for skp in SKIP:
        if skp in txt:
            return True
    return False


def loop(path, txt):
    for fnn in os.listdir(path):
        if not os.path.isdir(fnn):
            continue
        if not os.path.exists("%s/__init__.py" % fnn):
            continue
        os.chdir(fnn)
        for line in os.popen(txt).readlines():
            if doskip(line):
                continue
            print(line.rstrip())
        os.chdir("..")


if __name__ == "__main__":
    os.popen("fin/clean").readlines()
    loop(os.getcwd(), "pylint -d %s *" % IGNORE)
