#!/usr/bin/env python3
# This file is placed in the Public Domain.


import os
import sys


SKIP = ["---", "Your code"]
TODO = ["bin", "cin", "din"]
IGNORE = "C,R,E0402,E0401,E1101,W0201,W0703,W0613,W0108,W0406,W0212,W0622"


def doskip(txt):
    if not txt.strip():
        return True
    for skp in SKIP:
        if skp in txt:
            return True
    return False


def popen(txt):
    print(txt)
    sys.stdout.flush()
    for line in os.popen(txt).readlines():
        if doskip(line):
            print(line.strip())
        sys.stdout.flush()


if __name__ == "__main__":
    popen("din/clean")
    for tdo in TODO:
        popen("pylint -v -d %s %s" % (IGNORE, tdo))
